### ISSUE TITLE
How to access group information

### ISSUE THREAD

**Issue by shrikanthnext** [zquestz/omniauth-google-oauth2#446] opened 2023-06-02 03:10 UTC
```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, 'CLIENT_ID', 'CLIENT_SECRET',
    scope: 'email, https://www.googleapis.com/auth/admin.directory.group.readonly'
end

```
```
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    groups = auth.extra.raw_info.groups
    # Process the groups data as needed
    # ...
  end
end
```
My config looks above.
when I inspect groups, its coming as nil. can you please advise.

**Comment by shrikanthnext** [comment] 2023-06-06 10:21
@dpickett @will @mkdynamic @yury 
Anyone available to help with this query?

**Comment by zquestz** [comment] 2023-06-06 23:05
This is just the raw data coming back from Google. We don't filter it. Not sure what the cause is.

**Comment by zquestz** [comment] 2024-05-06 09:04
Adding a scope just makes sure your token can read the data, not that it will be included! You will need to make another call to access the group data.

**Closed by zquestz** 2024-05-06 09:04 UTC
