### ISSUE TITLE
JWT::InvalidIatError at /user/auth/google_oauth2/callback Invalid iat

### ISSUE THREAD

**Issue by simkessy** [zquestz/omniauth-google-oauth2#197] opened 2015-10-04 21:49 UTC
I'm getting this error while trying to log in using omniauth details can be  found here 

http://stackoverflow.com/questions/32938534/jwtinvalidiaterror-at-user-auth-google-oauth2-callback-invalid-iat

**Comment by zquestz** [comment] 2015-10-05 18:07
This was fixed in the latest release. If you are experiencing issues just pass :skip_jwt => true to the options you give the strategy and it will bypass this logic.

**Closed by zquestz** 2015-10-05 18:07 UTC

**Comment by simkessy** [comment] 2015-10-14 17:15
that seems to have worked, thank you

**Comment by Harryandrew** [comment] 2015-10-15 13:25
Where and into which document does `:skip_jwt =>` go?

**Comment by simkessy** [comment] 2015-10-16 06:37
@Harryandrew I put mine in the devise config:

`config.omniauth :google_oauth2, ENV["GOOGLE_ID"], ENV["GOOGLE_SECRET"], skip_jwt: true`

**Comment by nlsrchtr** [comment] 2016-02-29 11:03
@zquestz In which version of the gem this should be fixed? I tried with `0.3.1` and with the master branch? The error still exists. Thanks for your feedback.

**Comment by jwmeigs** [comment] 2016-03-29 21:18
@nlsrchtr   I just ran into this during a very messy Rails 4 upgrade... updated the gem to 0.4.1 and it works.

**Comment by zquestz** [comment] 2016-03-29 21:20
Glad to know the new version worked well for you. Feedback is always greatly appreciated!

**Comment by nlsrchtr** [comment] 2016-03-30 08:37
@jwmeigs Thanks for your notice! Works great with the updated version.
@zquestz Thanks for your time and effort. The new version resolves the issue for me.

**Comment by clod81** [comment] 2016-07-10 21:46
I'm running Rails `5` and gem version `0.4.1`, and I still get the `Invalid iat` error. It works if I `skip_jwt`.

**Comment by jvenezia** [comment] 2016-07-21 16:05
Is there a way to solve this without bypassing jwt?

**Comment by zquestz** [comment] 2016-07-21 16:31
You can increase the leeway time by adjusting `jwt_leeway`. The default is 60 seconds. Seems your servers and clients don't have time synchronized with NTP.

**Comment by hunainkapadia** [comment] 2016-07-24 13:52
How do you increase leeway time?

**Comment by zquestz** [comment] 2016-07-24 20:46
The docs have info on how to set it. Just check out the README.

```
jwt_leeway: Number of seconds passed to the JWT library as leeway. Defaults to 60 seconds.
```

Just pass it in when you are configuring the initializer.

**Comment by clod81** [comment] 2016-07-24 20:47
The server time out of sync of 2 minutes was the cause of the issue. It makes sense, thanks 👍

**Comment by pitops** [comment] 2016-10-25 12:32
@clod81 how can i check if the server is out of sync as u say? I am using ubuntu

**Comment by pitops** [comment] 2016-10-25 13:56
For those still wondering how to solve this. Instead of this
```
config.omniauth :google_oauth2, ENV["GOOGLE_ID"], ENV["GOOGLE_SECRET"], skip_jwt: true
```

The problem for me at least was in the ubuntu hardware clock. There is way to fix that

```
sudo ntpdate ntp.ubuntu.com
```

setup cronjob to check every hour and fix it

```
sudo nano /etc/cron.hourly/ntpdate
```

add

```
#! /bin/sh

ntpdate ntp.ubuntu.com
```
save file and change permissions

```
sudo chmod +x /etc/cron.hourly/ntpdate
```

**Comment by alxppp** [comment] 2017-05-30 06:22
For people running on Docker: `/usr/local/bin/docker run --rm --privileged alpine hwclock -s` syncs time with the host OS

**Comment by designium** [comment] 2019-11-30 02:18
I'm using Mac and I made some updates via brew and also some gems updates; then I'm getting this error right now. The omniauth was working fine before the whole set of updates:

    JWT::InvalidIatError
    Invalid iat

          iat = @payload['iat']
          raise(JWT::InvalidIatError, 'Invalid iat') if !iat.is_a?(Numeric) || iat.to_f > Time.now.to_f
        end
    
        def verify_iss

Here's the look of my gem list:

source 'https://rubygems.org'
      git_source(:github) { |repo| "https://github.com/#{repo}.git" }

      ruby '2.6.1'

      # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
      gem 'rails', '6.0.0'
      # Use sqlite3 as the database for Active Record
      gem 'sqlite3', '~> 1.4'
      # Use Puma as the app server
      gem 'puma', '~> 4.1'
      # Use SCSS for stylesheets
      gem 'sass-rails', '>= 6'
      # Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
      gem 'webpacker', '~> 4.0'
      # Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
      gem 'turbolinks', '~> 5'
      # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
      gem 'jbuilder', '~> 2.7'
      # Use Redis adapter to run Action Cable in production
      # gem 'redis', '~> 4.0'
      # Use Active Model has_secure_password
      # gem 'bcrypt', '~> 3.1.7'

      # Use Active Storage variant
      # gem 'image_processing', '~> 1.2'

      # Reduces boot times through caching; required in config/boot.rb
      gem 'bootsnap', '>= 1.4.2', require: false

      group :development, :test do
        # Call 'byebug' anywhere in the code to stop execution and get a debugger console
        gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
      end

      group :development do
        # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
        gem 'web-console', '>= 3.3.0'
        gem 'listen', '>= 3.0.5', '< 3.2'
        # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
        gem 'spring'
        gem 'spring-watcher-listen', '~> 2.0.0'
      end

      group :test do
        # Adds support for Capybara system testing and selenium driver
        gem 'capybara', '>= 2.15'
        gem 'selenium-webdriver'
        # Easy installation and use of web drivers to run system tests with browsers
        gem 'webdrivers'
      end

      # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
      gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

      # Chim's gems

      gem 'paper_trail'
      gem 'devise'
      gem 'rails_admin', '~> 2.0', git: 'https://github.com/sferik/rails_admin.git', ref: '03baf7281cfbe1ca9aeef9648a7d763107dc8f30'
      gem 'cancancan'
      gem 'carrierwave', '~> 2.0'
      gem 'bootstrap',  '~>4.3.1'
      gem "omniauth-google-oauth2"
      # gem 'browser'


Not sure what is causing this issue to happen.
