### ISSUE TITLE
JWT::InvalidIssuerError

### ISSUE THREAD

**Issue by koyakei** [zquestz/omniauth-google-oauth2#296] opened 2017-07-25 08:56 UTC
https://stackoverflow.com/questions/45271730/jwtinvalidissuererror-invalid-issuer-expected-accounts-google-com-received/45279087#45279087

I hit same problem. Is there anyone else?

**Comment by EtienneDepaulis** [comment] 2017-07-25 14:08
Same here :(

**Comment by RyanBrushett** [comment] 2017-07-25 20:50
See this: https://github.com/zquestz/omniauth-google-oauth2/issues/292

**Comment by gfx** [comment] 2017-07-26 01:33
It's fixed with downgrading to v0.5.0, which keeps `verify_iss: true`.

I suspect https://github.com/zquestz/omniauth-google-oauth2/pull/286 which seems to be included in v0.5.1.

**Comment by zquestz** [comment] 2017-07-30 01:09
I am working on a 0.6.0 release that bumps the JWT gem to 2.0 and can handle multiple iss values. Till then I would recommend using 0.5.0 if that is working. =)

**Comment by zquestz** [comment] 2017-07-30 01:27
Unfortunately the only version of `jwt` that contains the fix is master... The latest on rubygems is 2.0.0.beta1 from February. We will need to wait for jwt 2.0.0 to be published to get v0.6.0 out. For now I am considering reverting the URL commit... I can put those changes back when the jwt fixes are available. Does that sound reasonable to everyone?

**Comment by zquestz** [comment] 2017-07-30 22:08
0.5.2 has been pushed reverting changes to `authorize_url` and `token_url`. I will change the endpoints back once jwt 2.0 ships.

**Comment by mnussbaumer** [comment] 2017-08-05 16:07
Hi,
this:

```
JWT.decode(
            access_token['id_token'], nil, false, verify_iss: options.verify_iss,
                                                  iss: 'accounts.google.com',
                                                  verify_aud: true,
                                                  aud: options.client_id,
                                                  verify_sub: false,
                                                  verify_expiration: true,
                                                  verify_not_before: true,
                                                  verify_iat: true,
                                                  verify_jti: false,
                                                  leeway: options[:jwt_leeway]
          ).first
```

if `:iss` is changed to `'https://accounts.google.com'` it works as expected. 
Can I open a pr? I believe the issuer will always be https://... from now on, on behalf of google right?

**Comment by zquestz** [comment] 2017-08-07 01:44
This is already fixed in 0.5.2. Unfortunately just changing the value doesn't work for everyone. They still return both values. The new version actually goes back to the older endpoints that don't have this behavior.

**Comment by mnussbaumer** [comment] 2017-08-07 08:11
@zquestz indeed I noticed after but still left the PR open - as the change was different from the previous ones. Just to see if I understand this correctly, the problem is that `jwt` is using the returned value as is, instead of stripping the protocol part and then matching?

**Comment by zquestz** [comment] 2017-08-07 09:54
Nope, that isn't the issue. The issue is the new google endpoints return either https://accounts.google.com OR accounts.google.com and it can't be predicted. The new version of jwt allows the value to be an array, but is not available yet.

**Comment by aguynamedben** [comment] 2018-12-07 20:03
@zquestz I'm not affected by this issue, but I was wondering why old Google token URLs were being used.

Re:
> Unfortunately the only version of jwt that contains the fix is master... The latest on rubygems is 2.0.0.beta1 from February. We will need to wait for jwt 2.0.0 to be published to get v0.6.0 out.

Now [jwt is up to 2.1.0](https://rubygems.org/gems/jwt/), FYI.

I can bump the jwt version to 2.1.0 and revert the revert (https://github.com/zquestz/omniauth-google-oauth2/commit/5c6a599d855cd2be6ec3cc7b8f036cacb8e79e25) to update Google URLs if that's all that needs to be done (anything else?)

**Comment by zquestz** [comment] 2018-12-07 23:47
I believe that is correct, we should also bump the version of the gem and make sure the example app included in the repo continues to function.

**Comment by zquestz** [comment] 2018-12-08 00:04
We updated the endpoints to the latest recommended from Google. That should solve this.

**Closed by zquestz** 2018-12-08 00:04 UTC

**Comment by yaodev778** [comment] 2019-02-14 16:04
I hit the same issue 
Gemfile.lock as follows
   omniauth (1.9.0)
      hashie (>= 3.4.6, < 3.7.0)
      rack (>= 1.6.2, < 3)
    omniauth-google-oauth2 (0.5.4)
      jwt (>= 1.5)
      omniauth (>= 1.1.1)
      omniauth-oauth2 (>= 1.5)
    omniauth-oauth2 (1.6.0)
      oauth2 (~> 1.1)
      omniauth (~> 1.9)
